# Project: zod_launcher
# Compiler: Default GCC compiler
# Compiler Type: MingW 3
# Makefile created by wxDev-C++ 7.3 on 01/01/11 21:24

WXLIBNAME = wxmsw28
CPP       = g++.exe
CC        = gcc.exe
WINDRES   = "windres.exe"
OBJ       = Objects/MingW/zod_launcherApp.o Objects/MingW/zod_launcherFrm.o Objects/MingW/common.o Objects/MingW/store_settings.o Objects/MingW/zod_launcher_private.res
LINKOBJ   = "Objects/MingW/zod_launcherApp.o" "Objects/MingW/zod_launcherFrm.o" "Objects/MingW/common.o" "Objects/MingW/store_settings.o" Objects/MingW/zod_launcher_private.res
LIBS      = -L"C:/Program Files/Dev-Cpp/Lib" -mwindows -l$(WXLIBNAME) -l$(WXLIBNAME)_gl -lwxtiff -lwxjpeg -lwxpng -lwxzlib -lwxregex -lwxexpat -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32 -lopengl32  
INCS      = -I"C:/Program Files/Dev-Cpp/Include"
CXXINCS   = -I"C:/Program Files/Dev-Cpp/lib/gcc/mingw32/3.4.5/include" -I"C:/Program Files/Dev-Cpp/include/c++/3.4.5/backward" -I"C:/Program Files/Dev-Cpp/include/c++/3.4.5/mingw32" -I"C:/Program Files/Dev-Cpp/include/c++/3.4.5" -I"C:/Program Files/Dev-Cpp/include" -I"C:/Program Files/Dev-Cpp/" -I"C:/Program Files/Dev-Cpp/include/common/wx/msw" -I"C:/Program Files/Dev-Cpp/include/common/wx/generic" -I"C:/Program Files/Dev-Cpp/include/common/wx/html" -I"C:/Program Files/Dev-Cpp/include/common/wx/protocol" -I"C:/Program Files/Dev-Cpp/include/common/wx/xml" -I"C:/Program Files/Dev-Cpp/include/common/wx/xrc" -I"C:/Program Files/Dev-Cpp/include/common/wx" -I"C:/Program Files/Dev-Cpp/include/common"
RCINCS    = --include-dir "C:/PROGRA~1/Dev-Cpp/include/common"
BIN       = Output/MingW/zod_launcher.exe
DEFINES   = -D__WXMSW__ -D__GNUWIN32__ -D__WIN95__
CXXFLAGS  = $(CXXINCS) $(DEFINES) -fno-exceptions -fno-pcc-struct-return -fstrict-aliasing -Wall -D__WXMSW__ -D__GNUWIN32__ -D__WIN95__   -fexpensive-optimizations -O3
CFLAGS    = $(INCS) $(DEFINES) -fno-exceptions -fno-pcc-struct-return -fstrict-aliasing -Wall -D__WXMSW__ -D__GNUWIN32__ -D__WIN95__   -fexpensive-optimizations -O3
GPROF     = gprof.exe
RM        = rm -f
LINK      = g++.exe

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	$(RM) $(LINKOBJ) "$(BIN)"

$(BIN): $(OBJ)
	$(LINK) $(LINKOBJ) -o "$(BIN)" $(LIBS) 

Objects/MingW/zod_launcherApp.o: $(GLOBALDEPS) zod_launcherApp.cpp zod_launcherApp.h zod_launcherFrm.h
	$(CPP) -c zod_launcherApp.cpp -o Objects/MingW/zod_launcherApp.o $(CXXFLAGS)

Objects/MingW/zod_launcherFrm.o: $(GLOBALDEPS) zod_launcherFrm.cpp zod_launcherFrm.h store_settings.h
	$(CPP) -c zod_launcherFrm.cpp -o Objects/MingW/zod_launcherFrm.o $(CXXFLAGS)

Objects/MingW/common.o: $(GLOBALDEPS) common.cpp common.h
	$(CPP) -c common.cpp -o Objects/MingW/common.o $(CXXFLAGS)

Objects/MingW/store_settings.o: $(GLOBALDEPS) store_settings.cpp store_settings.h common.h
	$(CPP) -c store_settings.cpp -o Objects/MingW/store_settings.o $(CXXFLAGS)

Objects/MingW/zod_launcher_private.res: Objects/MingW/zod_launcher_private.rc zod_launcherApp.rc 
	$(WINDRES) --input-format=rc -o Objects/MingW/zod_launcher_private.res $(RCINCS) Objects/MingW/ZOD_LA~1.RC -O coff
